server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    keyId: LTAI5tPFwGhLstgM6244CEcX
    keySecret: NuwX8thyRMnetYIK9ZAgkeh3YhKRE9
    bucketName: service-oss-test